export const REQUEST_QUOTES='REQUEST_QUOTES'
export const GET_QUOTES_FAILURE='GET_QUOTES_FAILURE'
export const GET_QUOTES_SUCCESS='GET_QUOTES_SUCCESS'
export const GET_QUOTE_SUCCESS = "GET_QUOTE_SUCCESS"
export const REQUEST_QUOTE = 'REQUEST_QUOTE'
